# Generated by Django 4.2.8 on 2026-04-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0002_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
        migrations.AddField(
            model_name='post',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_posts', to='social_media_4P.group'),
        ),
        migrations.AddField(
            model_name='post',
            name='scope',
            field=models.CharField(choices=[('hotel', 'Toàn khách sạn'), ('groups', 'Theo nhóm')], default='hotel', max_length=20),
        ),
    ]
