# Generated by Django 4.2.8 on 2026-04-13 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0003_remove_post_group_post_groups_post_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['created_at'], 'verbose_name': 'Interaction', 'verbose_name_plural': 'Interactions'},
        ),
        migrations.AddField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
