# Generated by Django 4.2.8 on 2026-04-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0006_taskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.CharField(blank=True, choices=[('F&B', 'Food & Beverage'), ('HK', 'Housekeeping'), ('FO', 'Front Office')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='shift',
            field=models.CharField(choices=[('Sáng', 'Ca Sáng'), ('Chiều', 'Ca Chiều'), ('Tối', 'Ca Tối'), ('Cả ngày', 'Cả ngày')], default='Sáng', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
