# Generated by Django 4.2.8 on 2026-04-14 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0008_alter_task_options_task_work_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(choices=[('F&B', 'Food & Beverage'), ('HK', 'Housekeeping'), ('FO', 'Front Office')], max_length=10)),
                ('shift', models.CharField(choices=[('Sáng', 'Ca Sáng'), ('Chiều', 'Ca Chiều'), ('Tối', 'Ca Tối'), ('Cả ngày', 'Cả ngày')], default='Sáng', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'TaskTemplates',
                'ordering': ['department', 'order', 'shift'],
            },
        ),
    ]
