# Generated by Django 4.2.8 on 2026-04-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0010_meeting_created_at_meeting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='social_media_4P.group'),
        ),
    ]
