# Generated by Django 4.2.8 on 2026-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0011_meeting_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('group', 'Công khai'), ('private', 'Riêng tư'), ('department', 'Phòng ban')], default='group', max_length=20),
        ),
    ]
