# Generated by Django 6.0.1 on 2026-04-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0013_add_call_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
