# Generated by Django 4.2.8 on 2026-04-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0013_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social_media_4P.interaction'),
        ),
    ]
