# Generated by Django 6.0.1 on 2026-04-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0005_remove_post_image_remove_post_video_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
