# Generated by Django 4.2.8 on 2026-04-14 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0007_task_department_task_end_time_task_shift_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-work_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='work_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
