# Generated by Django 6.0.1 on 2026-04-20 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0012_conversation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('calling', 'Đang gọi'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Đã từ chối'), ('missed', 'Nhỡ máy'), ('ended', 'Đã kết thúc')], default='calling', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='social_media_4P.conversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CallRequests',
                'ordering': ['-created_at'],
            },
        ),
    ]
