# Generated by Django 4.2.8 on 2026-04-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0012_group_status_add_department'),
        ('social_media_4P', '0014_interaction_parent'),
    ]

    operations = [
    ]
