# Generated by Django 6.0.1 on 2026-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0015_add_message_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Văn bản'), ('image', 'Hình ảnh'), ('file', 'Tệp đính kèm'), ('call', 'Cuộc gọi')], default='text', max_length=10),
        ),
    ]
