# Generated by Django 4.2.8 on 2026-04-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0015_merge_20260430_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='department',
            field=models.CharField(blank=True, help_text='Bộ phận: FO, F&B, HK', max_length=50, null=True),
        ),
    ]
