# Generated by Django 4.2.8 on 2026-05-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0016_add_message_type'),
        ('social_media_4P', '0016_meeting_department'),
    ]

    operations = [
    ]
