# Generated by Django 4.2.8 on 2026-05-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0017_merge_0016_add_message_type_0016_meeting_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('group', 'Group'), ('private', 'Private')], default='group', max_length=20),
        ),
    ]
