# Generated by Django 4.2.8 on 2026-05-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0018_remove_interaction_parent_remove_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='department',
        ),
    ]
