# Generated by Django 4.2.8 on 2026-05-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0019_remove_meeting_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
