# Generated by Django 4.2.8 on 2026-05-02 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_4P', '0020_conversationmember_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social_media_4P.interaction'),
        ),
    ]
